name: Update README

on:
  schedule:
    - cron: '0 1 * * *' # Every day at 01:00
  workflow_dispatch:

enable-email-notifications: true

jobs:
  update:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: https://github.com/jdx/mise-action@9e7f7633ff6f6d6048a9418a68d48f288f50eb14 # v4.2.3
        with:
          install: true
          cache: true
          experimental: true
      - name: Build README.md
        run: mise start
      - name: Commit
        run: |
          git config --global user.name 'Axel Leroy'
          git config --global user.email 'axeleroy@users.noreply.github.com'
          git config http.extraHeader "Authorization: Bearer ${{ env.FORGEJO_TOKEN }}"
          git add README.md
          git commit -am "Updated README" || exit 0
          git push 
          

