name: Update README

on:
  schedule:
    - cron: '0 1 * * *' # Every day at 01:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: 2024.12.14
          install: true
          cache: true
          experimental: true
      - name: Build README.md
        run: mise start
      - name: Commit
        run: |
          git config --global user.name 'Axel Leroy'
          git config --global user.email 'axeleroy@users.noreply.github.com'
          git add README.md
          git commit -am "Updated README" || exit 0
          git push
          

